# Generated by Django 5.0.2 on 2024-02-27 13:16

import django.db.models.deletion
import quizapp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField(default='Savol')),
                ('difficulty_level', models.IntegerField(default=1, validators=[quizapp.validators.validate_difficulty_question])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_right', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quizapp.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject_name',
            field=models.ForeignKey(default='Matematika', on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizapp.subject', to_field='name'),
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjectcategory', to='quizapp.subject', to_field='name')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subject_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quizapp.subjectcategory', to_field='name'),
        ),
        migrations.CreateModel(
            name='WrongAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wronganswers', to='quizapp.question')),
            ],
        ),
    ]
